# Generated by Django 6.0.2 on 2026-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visadocument',
            name='uploaded_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
