# Generated by Django 6.0.2 on 2026-03-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_visadocument_uploaded_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visadocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
