# Generated by Django 6.0.2 on 2026-03-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_visadocument_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visastage',
            name='medical_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
