# Generated by Django 6.0.2 on 2026-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0004_visastage_medical_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visastage',
            name='biometrics_booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visastage',
            name='biometrics_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
