# Generated by Django 6.0.2 on 2026-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0005_visastage_biometrics_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visastage',
            name='biometrics_status',
        ),
        migrations.AddField(
            model_name='visastage',
            name='lmia_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='visastage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
