# Generated by Django 6.0.2 on 2026-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0006_remove_visastage_biometrics_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visastage',
            name='lmia_payment_status',
        ),
        migrations.AddField(
            model_name='visastage',
            name='biometrics_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
