# Generated by Django 6.0.2 on 2026-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0007_remove_visastage_lmia_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visastage',
            name='decision_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
