# Generated by Django 6.0.2 on 2026-04-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0008_visastage_decision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visastage',
            name='medical_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
