# Generated by Django 6.0.2 on 2026-03-24 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='applications/cv/')),
                ('cover_letter', models.FileField(upload_to='applications/cover_letters/')),
                ('passport_photo', models.ImageField(upload_to='applications/passports/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='applications/others/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='applied', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('payment_verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_rejection_reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='listings.joblisting')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'job')},
            },
        ),
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(default='job_offer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visa', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='VisaStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='temp', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('visa_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='applications.visaapplication')),
            ],
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='visa_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='applications.visastage')),
            ],
        ),
    ]
