# Generated by Django 6.0.2 on 2026-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewed', 'Reviewed'), ('assessment', 'Assessment'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='applied', max_length=20),
        ),
    ]
