# Generated by Django 6.0.2 on 2026-03-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visastage',
            name='visa_application',
        ),
        migrations.RemoveField(
            model_name='visadocument',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='visadocument',
            name='user',
        ),
        migrations.DeleteModel(
            name='VisaApplication',
        ),
        migrations.DeleteModel(
            name='VisaStage',
        ),
        migrations.DeleteModel(
            name='VisaDocument',
        ),
    ]
