# Generated by Django 6.0.2 on 2026-02-21 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='certificates',
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(default=django.utils.timezone.now, upload_to='applications/cover_letters/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='applications/others/'),
        ),
    ]
