# Generated by Django 6.0.2 on 2026-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
