# Generated by Django 6.0.2 on 2026-02-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_payment_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
