# Generated by Django 6.0.2 on 2026-02-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentmethod_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='code',
        ),
    ]
