# Generated by Django 6.0.2 on 2026-02-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_payment_status'),
        ('payments', '0003_remove_paymentmethod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='applications.application'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('resume', 'Resume Writing'), ('cover_letter', 'Cover Letter Writing'), ('application_fee', 'Application Processing Fee')], max_length=20),
        ),
    ]
