# Generated by Django 6.0.2 on 2026-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('resume', 'Resume Writing'), ('cover_letter', 'Cover Letter Writing'), ('application_fee', 'Application Processing Fee'), ('lmia_fee', 'LMIA Processing Fee'), ('visa_fee', 'Visa Processing Fee'), ('upgrade', 'Upgrade to Premium')], max_length=20),
        ),
    ]
