# Generated by Django 6.0.2 on 2026-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='documenttype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
