# Generated by Django 6.0.2 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_link', models.URLField(blank=True, null=True)),
                ('is_whatsapp_active', models.BooleanField(default=True)),
            ],
        ),
    ]
