# Generated by Django 6.0.2 on 2026-02-17 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location_city', models.CharField(max_length=100)),
                ('location_province', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=50)),
                ('hours_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('work_mode', models.CharField(choices=[('on_site', 'On Site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('permanent', 'Permanent')], max_length=20)),
                ('vacancies', models.PositiveIntegerField(default=1)),
                ('start_date', models.CharField(blank=True, max_length=100)),
                ('benefits', models.TextField(blank=True)),
                ('languages', models.CharField(blank=True, max_length=255)),
                ('education', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=255)),
                ('work_environment', models.TextField(blank=True)),
                ('work_setting', models.CharField(blank=True, max_length=255)),
                ('responsibilities', models.TextField(blank=True)),
                ('supervision', models.CharField(blank=True, max_length=255)),
                ('specialization', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='listings.tag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location_city'], name='listings_jo_locatio_51db05_idx'), models.Index(fields=['location_province'], name='listings_jo_locatio_49734f_idx'), models.Index(fields=['created_at'], name='listings_jo_created_1be592_idx'), models.Index(fields=['expires_at'], name='listings_jo_expires_d97b3e_idx')],
            },
        ),
    ]
