# Generated by Django 6.0.2 on 2026-04-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='joblisting',
            name='listings_jo_expires_d97b3e_idx',
        ),
        migrations.RemoveField(
            model_name='joblisting',
            name='expires_at',
        ),
    ]
