# Generated by Django 6.0.2 on 2026-02-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_birth',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
